[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "mpmath>=1.3.0",
    "numpy>=2.2.6",
    "scipy>=1.15.3",
    "sympy>=1.14.0",
]
